### ISSUE TITLE
Wrong doc about default JS URL

### ISSUE THREAD

**Issue by merwok** [browniebroke/django-tinymce4-widget#539]
Hello and thanks for maintaining this fork!

There’s a conflict between readme and docs:

(readme)
> The main difference with the original fork is that it does not include any static files, it’s using the TinyMCE from the CDN by default.

(https://github.com/browniebroke/django-tinymce4-widget/blob/main/docs/configuration.md?plain=1#L37)
>TINYMCE_JS_URL – a path to TinyMCE JavaScript library. Default: your_static_url/tinymce/js/tinymce/tinymce.min.js.

**Comment by merwok** [comment]
tinymce 4 is deprecated and the CDN shutdown 🙁

**Comment by merwok** [comment]
@browniebroke There was a release just now, I am curious as my understanding was that tinymce v4 can’t be used anymore.

**Comment by browniebroke** [comment]
> tinymce 4 is deprecated and the CDN shutdown 🙁

~Might be deprecated, but the CDN is not shutdown, the above JS file still loads for me.~ The docs if this package might have some mistakes that I haven't updated properly, I accept PR to fix them.

But to be entiroely honest, I'm not really using this anymore. It's pretty much in maintenance mode, and I'm only upgrading the Python/Django versions as they come out.

**Comment by browniebroke** [comment]
> Might be deprecated, but the CDN is not shutdown, the above JS file still loads for me.

Ok, I take that back :) The JS file loads, but its content is a deprecation notice.

**Comment by merwok** [comment]
I understand. At least this package is useful to allow devs to update to newer Django versions without breaking or squashing migrations! Then the problem of HTML fields can be solved later.

**Comment by browniebroke** [comment]
I was wondering the best way forward, andhere are the options that I ran through:

1. Deprecate this package and stop its support entirely, especially if the JS isn't hosted on a CDN. One of the main driver of this fork was to use static files from a CDN. 
2. Upgrade it to TinyMCE 5 or 6: would need a package rename, as it has tinymce4 in the name.  I don't want to do (as I said, I'm no longer using this), and anyone can fork and do it themselves: there is no need to transfer.
3. Do the minimal fix to make it work again by finding another CDN with the required files. It seems like the static files for v4 are hosted elsewhere now: https://www.tiny.cloud/docs-4x/quick-start/#step1includethetinymcescript - seems like a small fix and meaning I can keep it running for a bit longer.

Would be nice to put a notice up in the various places (GitHub, PyPI, documentation) that TinyMCE 4 is deprecated and suggest more modern alternatives. What do you think?

**Comment by merwok** [comment]
3 wouldn’t solve it: even with the JS file restored to a static file or CDN, the connection to tinymce 4 service would not work.

So a proper migration (idea 2) for HTML fields is the way forward. Btw I have also used ckeditor on other projects, it has the advantage of doing its work in javascript without connecting to a service, but doesn’t have a great image upload module.

**Comment by merwok** [comment]
Idea 2 exists! https://github.com/jazzband/django-tinymce
